<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Curriculum.Core\Curriculum.Core.csproj" />
      <ProjectReference Include="..\Curriculum.Infrastructure\Curriculum.Infrastructure.csproj" />
    </ItemGroup>

</Project>
