<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GraphQL.Server.All" Version="8.3.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Curriculum.Infrastructure\Curriculum.Infrastructure.csproj" />
      <ProjectReference Include="..\Curriculum.Services\Curriculum.Services.csproj" />
    </ItemGroup>

</Project>
